# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Fulltimeteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=15)),
                ('year', models.CharField(max_length=10)),
                ('class_num', models.IntegerField()),
                ('g_pf_name', models.CharField(blank=b'true', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myclass_name', models.CharField(max_length=45)),
                ('m_grade_name', models.CharField(max_length=15)),
                ('m_pf_name', models.CharField(max_length=30)),
                ('myclass_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parttimeteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profess_subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_name', models.CharField(max_length=30)),
                ('ms_pf_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_name', models.CharField(max_length=30)),
                ('dp_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Public_subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Schoolplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=b'true', max_length=30)),
                ('building_floor', models.CharField(blank=b'true', max_length=30)),
                ('schoolplace_name', models.CharField(max_length=30)),
                ('schoolplace_num', models.CharField(blank=b'true', max_length=10)),
                ('max_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Substituteteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=30)),
            ],
        ),
    ]
