# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makebaseclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseclass_name', models.CharField(max_length=30)),
                ('basegrade_name', models.CharField(max_length=30)),
                ('baseclass_year', models.CharField(max_length=30)),
                ('baseclass_num', models.IntegerField(default=0)),
                ('baseprofess_name', models.CharField(max_length=30)),
                ('basedepart_name', models.CharField(max_length=30)),
                ('schoolplace_class', models.CharField(blank='true', max_length=30)),
                ('baseclass_stunum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Makegradetp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank='true', max_length=30)),
                ('profess', models.CharField(blank='true', max_length=30)),
                ('public_subject', models.CharField(max_length=30)),
                ('profess_subject', models.CharField(max_length=30)),
                ('theory_classes', models.IntegerField(default=0)),
                ('practice_classes', models.IntegerField(default=0)),
                ('prior_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Maketeachsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=30)),
                ('teacher_type', models.CharField(max_length=30)),
                ('profess_subject', models.CharField(blank='true', max_length=30)),
                ('public_subject', models.CharField(blank='true', max_length=30)),
                ('max_classes', models.IntegerField(default=30)),
                ('min_classes', models.IntegerField(default=0)),
                ('must_time', models.CharField(blank='true', max_length=30)),
                ('unable_time', models.CharField(blank='true', max_length=30)),
            ],
        ),
    ]
