# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setrule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makegradetp',
            old_name='profess_subject',
            new_name='subject_name',
        ),
        migrations.RenameField(
            model_name='makegradetp',
            old_name='public_subject',
            new_name='subject_type',
        ),
    ]
