# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setrule', '0002_auto_20180814_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makegradetp',
            name='subject_type',
            field=models.CharField(blank='true', max_length=30),
        ),
    ]
