# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setrule', '0003_auto_20180815_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='makegradetp',
            name='depart',
            field=models.CharField(blank='true', max_length=30),
        ),
    ]
