# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setrule', '0004_makegradetp_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='makebaseclass',
            name='msubject',
            field=models.CharField(blank='true', max_length=30),
        ),
        migrations.AddField(
            model_name='makebaseclass',
            name='mteacher_name',
            field=models.CharField(blank='true', max_length=30),
        ),
    ]
